---
title: "Online Pre-Registration System"
author: "Marivic Amuan, Nicole De Luna, Reysha Marie Salinas BSIT 2-C"
date: "2024-04-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


load/Read the responses.

```{r eval=FALSE}
library(readr)
library(dplyr)
library(readxl)

response <- read_excel ("response.xlsx")
View(response)
summary(response)
```

----------DEMOGRAPHICS--------------
Demographics: Gender 
```{r}
gender <- table(response$Gender)  # Creates a frequency table

gender <- as.data.frame(gender)  # Converts to a data frame

gender  # View the data frame (optional)

ggplot(gender, aes(x = Var1, y = Freq)) +  
  geom_bar(stat = "identity") +  
  labs(title = "Distribution of Gender",  
       x = "Gender",
       y = "Frequency") +
  theme_classic() 

  ggsave("gender_Demographics.png") 

 
```
Demographics:Age
```{r}
age <- table(response$Age)

age <- as.data.frame(age)
age

ggplot(age, aes(x = factor(Var1), y = Freq)) + 
  geom_bar(stat = "identity") + 
  labs(title = "Age of Respondent", x = "Age Group", y = "Frequency") 


   ggsave("age_Demographics.png") 
```
Demographics:School 
```{r}
library(dplyr)
library(ggplot2)  


school_data <- response$School 
schooldf <- data.frame(school = school_data)

schooldf$school <- toupper(trimws(schooldf$school))  


school_counts <- schooldf %>%
  group_by(school) %>%
  summarise(count = n()) %>%
  arrange(desc(count))  


ggplot(school_counts, aes(x = factor(school), y = count)) +
  geom_bar(stat = "identity") +
  labs(title = "School of Respondents", x = "School", y = "Frequency") +
  theme(axis.text.x = element_text(angle = 55, hjust = 1))

ggsave("school_Demographics.png", width = 20, height = 10) 
```
Demographics:Time
```{r}
time <-table(response$Timestamp)

time <- as.data.frame(time)

time$Var1 <- strptime(time$Var1, format = "%Y-%m-%d %H:%M:%S")  # Parse timestamps
time$Var1 <- format(time$Var1, format = "%b %d, %Y %H:%M") 

ggplot(time, aes(x = Var1, y = Freq)) +
  geom_bar(stat = "identity") +  
  labs(title = "Frequency of Timestamps", x = "Timestamp", y = "Frequency") +
  theme(axis.text.x = element_text(angle =90, hjust = ,  size = 5)) 


  ggsave("timestamp_Demographics.png")  #SAVE PNG
  
```
Demographics:Department&course
```{r}
department<-table(response$`Department&course`)


# table to a data frame 
department_df <- as.data.frame(department)
department_df <- department_df %>%
  mutate(Department_Course = rownames(department_df))  

#bar chart
ggplot(department_df, aes(x = Var1, y = Freq)) +
  geom_bar(stat = "identity") + 
  labs(title = "Frequency of Department and Course Combinations",
       x = "Department & Course",  
       y = "Frequency") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 5)) 

# Display the chart
 ggsave("Department&course_Demographics.png")  

```
Demographics:Year&Section
```{r}
yearSec <- table(response$`Year&Section`)

yearSec_df <- as.data.frame(yearSec)
yearSec_df <- yearSec_df %>%
  mutate(Year_Section = rownames(yearSec_df))  


ggplot(yearSec_df, aes(x = Var1, y = Freq)) +
  geom_bar(stat = "identity") +  
  labs(title = "Frequency of Year and Section Combinations",
       x = "Year & Section", 
       y = "Frequency") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 5)) 


  ggsave("Year&Section_Demographics.png")
```

----------DETERMINANT----------------
Create data frame for questions.
```{r}
#Create data frame for questions.
  questions_column <- response[, 10:39]
write_csv(questions_column, file = "questions.csv")

#read survey
data <- read.csv("questions.csv")

#mean of all survey questions
numeric_cols <- sapply(data, is.numeric)

means <- colMeans(data[, numeric_cols], na.rm = TRUE)

colnames(data)[numeric_cols]  

all_means <-mean(means)

#mean of the suvey question is  2.516013

```
--------Mean and Standard Deviation-----
Performance Expectancy
```{r}
# Read the data 
data <- read.csv("questions.csv")

columns <- data[, 1:4]  

# Calculate the mean and standard deviation

mean <-mean(performance)
stds <- sd(performance)

cat("Means :\n", mean)

#Means  Performance Expectancy
 #2.421569

cat("\nStandard Deviations:\n", stds)

#Standard Deviations /Performance Expectancy
# 0.05125617

```
Effort Expectancy
```{r}
# Read the data 
data <- read.csv("questions.csv")

columns <- data[, 5:8]  

# Calculate the mean and standard deviation 
performance <- colMeans(columns) 
stds <- apply(columns, 2, sd)  

mean <-mean(performance)
stds <- sd(performance)

cat("Means :\n", mean)

#Means for Effort Expectancy
 #2.514706


cat("\nStandard Deviations:\n", stds)

#Standard Deviations for Effort Expectancy
 #0.06862745

```
Attitude Toward Using Technology
```{r}
# Read the data 
data <- read.csv("questions.csv")

columns <- data[, 9:12]  

# Calculate the mean and standard deviation 
performance <- colMeans(columns) 
stds <- apply(columns, 2, sd)  

mean <-mean(performance)
stds <- sd(performance)

cat("Means:\n", mean)

#Means for Attitude Toward Using Technology
 # 2.473039


cat("\nStandard Deviations:\n", stds)

#Standard Deviations for Attitude Toward Using Technology
 #0.04411765
```
Social influence
```{r}

columns <- data[, 13:16]  

# Calculate the mean and standard deviation 
performance <- colMeans(columns) 
stds <- apply(columns, 2, sd)  

mean <-mean(performance)
stds <- sd(performance)

cat("Means:\n", mean)

#Means for Social influence
 #  2.54902


cat("\nStandard Deviations:\n", stds)

#Standard Deviations for Social influence
 #0.06252002
```
Facilitating Conditions
```{r}

columns <- data[, 17:20]  

# Calculate the mean and standard deviation 
performance <- colMeans(columns) 
stds <- apply(columns, 2, sd)  

mean <-mean(performance)
stds <- sd(performance)

cat("Means:\n", mean)

#Means for Facilitating Conditions
 #2.477941



cat("\nStandard Deviations:\n", stds)

#Standard Deviations for Facilitating Conditions
 #0.05023015
```
Self-Efficacy
```{r}

columns <- data[, 21:24]  

# Calculate the mean and standard deviation 
performance <- colMeans(columns) 
stds <- apply(columns, 2, sd)  

mean <-mean(performance)
stds <- sd(performance)

cat("Means:\n", mean)

#Means for Self-Efficacy
 # 2.544118


cat("\nStandard Deviations:\n", stds)

#Standard Deviations for Self-Efficacy
 #0.09214296
```
Anxiety
```{r}

columns <- data[, 25:28]  

# Calculate the mean and standard deviation 
performance <- colMeans(columns) 
stds <- apply(columns, 2, sd)  

mean <-mean(performance)
stds <- sd(performance)

cat("Means:\n", mean)

#Means for Anxiety
 # 2.632353


cat("\nStandard Deviations:\n", stds)

#Standard Deviations for Anxiety
 #0.0404226
```
Behavioral Intention to Use the System
```{r}

columns <- data[, 29:30]  

# Calculate the mean and standard deviation 
performance <- colMeans(columns) 
stds <- apply(columns, 2, sd)  

mean <-mean(performance)
stds <- sd(performance)

cat("Means:\n", mean)

#Means for Behavioral Intention to Use the System
 #  2.514706


cat("\nStandard Deviations:\n", stds)

#Standard Deviations for Behavioral Intention to Use the System
 # 0.02079726
```




